POST http://localhost:7777/api/v1/courses
Content-Type: application/json

{
  "title": "Curso nuevo",
  "description": "Descripción del curso 3",
  "amount": 10.2,
  "version": 2,
  "duration": 31,
  "languageId": 2,
  "levelId": 2,
  "subCategoryId": 3,
  "professorKeycloakId": "d4ab900f-3fe0-44ba-aacd-4ad74a7738ce"
}
###
GET http://localhost:7777/api/v1/courses?page=0&size=15

###
GET http://localhost:7777/api/v1/courses?page=0&size=3&title=Curso
###
GET http://localhost:7777/api/v1/courses?page=0&size=3&languageId=1
###

GET http://localhost:7777/api/v1/courses?page=0&size=3&levelId=2
###
GET http://localhost:7777/api/v1/courses?page=0&size=3&categoryId=1

###
GET http://localhost:7777/api/v1/courses/professor/d4ab900f-3fe0-44ba-aacd-4ad74a7738ce