POST http://localhost:7777/api/v1/course/2/create-channel

###
GET http://localhost:7777/api/v1/course/3/channel/verification
###
GET http://localhost:7777/api/v1/course/2/channel/stream
###
GET http://localhost:7777/api/v1/course/2/channel/playback
