POST http://localhost:7777/progress?routingKey=progress.routingKey
Accept: application/json
Content-Type: application/json

{
  "userKeyCloakId": "1a24bde3-0423-42b7-9e21-c567ae2b3363",
  "courseId": 8,
  "classId": 12
}
