server:
  port: 8972

spring:
  application:
    name: ms-course
  datasource:
    #url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cognito-hub}
    url: jdbc:postgresql://localhost:5432/cognito
    username: ${DB_USERNAME:postgres}
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/