server:
  port: 7777

spring:
  application:
    name: ms-course
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cognito-hub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/