server:
  port: 7777

spring:
  application:
    name: ms-course
  datasource:
    #url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cognito-hub}
    url: jdbc:postgresql://localhost:5432/cognito
    username: ${DB_USERNAME:postgres}
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

keycloak:
  auth-server-url: http://localhost:8080
  credentials:
    secret: xLnnPpvGRBkekbUuVLnnudrkSVDTCzFc
    realm: cognito-hub

token:
  converter:
    principal-attribute: preferred_username
    resource-id: cognito-hub